# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:29:03+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class ASN1PrintableString64(
    RootModel[constr(pattern=r'[a-zA-Z0-9\'()+-.?:/= ]*', min_length=0, max_length=64)]
):
    root: constr(pattern=r'[a-zA-Z0-9\'()+-.?:/= ]*', min_length=0, max_length=64)


class AWSPolicy(
    RootModel[
        constr(
            pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]+',
            min_length=1,
            max_length=20480,
        )
    ]
):
    root: constr(
        pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]+', min_length=1, max_length=20480
    )


class AccessMethodType(Enum):
    CA_REPOSITORY = 'CA_REPOSITORY'
    RESOURCE_PKI_MANIFEST = 'RESOURCE_PKI_MANIFEST'
    RESOURCE_PKI_NOTIFY = 'RESOURCE_PKI_NOTIFY'


class AccountId(RootModel[constr(pattern=r'[0-9]+', min_length=12, max_length=12)]):
    root: constr(pattern=r'[0-9]+', min_length=12, max_length=12)


class ActionType(Enum):
    IssueCertificate = 'IssueCertificate'
    GetCertificate = 'GetCertificate'
    ListPermissions = 'ListPermissions'


class Arn(
    RootModel[
        constr(
            pattern=r'arn:[\w+=/,.@-]+:[\w+=/,.@-]+:[\w+=/,.@-]*:[0-9]*:[\w+=,.@-]+(/[\w+=,.@-]+)*',
            min_length=5,
            max_length=200,
        )
    ]
):
    root: constr(
        pattern=r'arn:[\w+=/,.@-]+:[\w+=/,.@-]+:[\w+=/,.@-]*:[0-9]*:[\w+=,.@-]+(/[\w+=,.@-]+)*',
        min_length=5,
        max_length=200,
    )


class AuditReportId(
    RootModel[
        constr(
            pattern=r'[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}',
            min_length=36,
            max_length=36,
        )
    ]
):
    root: constr(
        pattern=r'[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}',
        min_length=36,
        max_length=36,
    )


class AuditReportResponseFormat(Enum):
    JSON = 'JSON'
    CSV = 'CSV'


class AuditReportStatus(Enum):
    CREATING = 'CREATING'
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'


class Base64String1To4096(
    RootModel[
        constr(
            pattern=r'^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$',
            min_length=1,
            max_length=4096,
        )
    ]
):
    root: constr(
        pattern=r'^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$',
        min_length=1,
        max_length=4096,
    )


class Boolean(RootModel[bool]):
    root: bool


class CertificateAuthorityStatus(Enum):
    CREATING = 'CREATING'
    PENDING_CERTIFICATE = 'PENDING_CERTIFICATE'
    ACTIVE = 'ACTIVE'
    DELETED = 'DELETED'
    DISABLED = 'DISABLED'
    EXPIRED = 'EXPIRED'
    FAILED = 'FAILED'


class CertificateAuthorityType(Enum):
    ROOT = 'ROOT'
    SUBORDINATE = 'SUBORDINATE'


class CertificateAuthorityUsageMode(Enum):
    GENERAL_PURPOSE = 'GENERAL_PURPOSE'
    SHORT_LIVED_CERTIFICATE = 'SHORT_LIVED_CERTIFICATE'


class CertificateBody(RootModel[str]):
    root: str


class CertificateBodyBlob(RootModel[constr(min_length=1, max_length=32768)]):
    root: constr(min_length=1, max_length=32768)


class CertificateChain(RootModel[str]):
    root: str


class CertificateChainBlob(RootModel[constr(min_length=0, max_length=2097152)]):
    root: constr(min_length=0, max_length=2097152)


class CertificateMismatchException(RootModel[Any]):
    root: Any


class CnameString(
    RootModel[
        constr(
            pattern=r'^[-a-zA-Z0-9;/?:@&=+$,%_.!~*()\']*$', min_length=0, max_length=253
        )
    ]
):
    root: constr(
        pattern=r'^[-a-zA-Z0-9;/?:@&=+$,%_.!~*()\']*$', min_length=0, max_length=253
    )


class ConcurrentModificationException(RootModel[Any]):
    root: Any


class CountryCodeString(
    RootModel[constr(pattern=r'[A-Za-z]{2}', min_length=2, max_length=2)]
):
    root: constr(pattern=r'[A-Za-z]{2}', min_length=2, max_length=2)


class CreateCertificateAuthorityResponse(BaseModel):
    CertificateAuthorityArn: Optional[Arn] = None


class CsrBlob(RootModel[constr(min_length=1, max_length=32768)]):
    root: constr(min_length=1, max_length=32768)


class CsrBody(RootModel[str]):
    root: str


class CustomObjectIdentifier(
    RootModel[
        constr(
            pattern=r'^([0-2])\.([0-9]|([0-3][0-9]))((\.([0-9]+)){0,126})$',
            min_length=0,
            max_length=64,
        )
    ]
):
    root: constr(
        pattern=r'^([0-2])\.([0-9]|([0-3][0-9]))((\.([0-9]+)){0,126})$',
        min_length=0,
        max_length=64,
    )


class DeletePolicyRequest(BaseModel):
    ResourceArn: Arn


class DescribeCertificateAuthorityAuditReportRequest(BaseModel):
    AuditReportId_1: AuditReportId = Field(..., alias='AuditReportId')
    CertificateAuthorityArn: Arn


class DescribeCertificateAuthorityRequest(BaseModel):
    CertificateAuthorityArn: Arn


class ExtendedKeyUsageType(Enum):
    SERVER_AUTH = 'SERVER_AUTH'
    CLIENT_AUTH = 'CLIENT_AUTH'
    CODE_SIGNING = 'CODE_SIGNING'
    EMAIL_PROTECTION = 'EMAIL_PROTECTION'
    TIME_STAMPING = 'TIME_STAMPING'
    OCSP_SIGNING = 'OCSP_SIGNING'
    SMART_CARD_LOGIN = 'SMART_CARD_LOGIN'
    DOCUMENT_SIGNING = 'DOCUMENT_SIGNING'
    CERTIFICATE_TRANSPARENCY = 'CERTIFICATE_TRANSPARENCY'


class FailureReason(Enum):
    REQUEST_TIMED_OUT = 'REQUEST_TIMED_OUT'
    UNSUPPORTED_ALGORITHM = 'UNSUPPORTED_ALGORITHM'
    OTHER = 'OTHER'


class GetCertificateAuthorityCertificateRequest(BaseModel):
    CertificateAuthorityArn: Arn


class GetCertificateAuthorityCertificateResponse(BaseModel):
    Certificate: Optional[CertificateBody] = None
    CertificateChain_1: Optional[CertificateChain] = Field(
        None, alias='CertificateChain'
    )


class GetCertificateAuthorityCsrRequest(BaseModel):
    CertificateAuthorityArn: Arn


class GetCertificateAuthorityCsrResponse(BaseModel):
    Csr: Optional[CsrBody] = None


class GetCertificateRequest(BaseModel):
    CertificateArn: Arn
    CertificateAuthorityArn: Arn


class GetCertificateResponse(BaseModel):
    Certificate: Optional[CertificateBody] = None
    CertificateChain_1: Optional[CertificateChain] = Field(
        None, alias='CertificateChain'
    )


class GetPolicyRequest(BaseModel):
    ResourceArn: Arn


class GetPolicyResponse(BaseModel):
    Policy: Optional[AWSPolicy] = None


class IdempotencyToken(
    RootModel[
        constr(
            pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]*', min_length=1, max_length=36
        )
    ]
):
    root: constr(
        pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]*', min_length=1, max_length=36
    )


class ImportCertificateAuthorityCertificateRequest(BaseModel):
    Certificate: CertificateBodyBlob
    CertificateAuthorityArn: Arn
    CertificateChain: Optional[CertificateChainBlob] = None


class Integer1To5000(RootModel[conint(ge=1, le=5000)]):
    root: conint(ge=1, le=5000)


class InvalidArgsException(RootModel[Any]):
    root: Any


class InvalidArnException(RootModel[Any]):
    root: Any


class InvalidNextTokenException(RootModel[Any]):
    root: Any


class InvalidPolicyException(RootModel[Any]):
    root: Any


class InvalidRequestException(RootModel[Any]):
    root: Any


class InvalidStateException(RootModel[Any]):
    root: Any


class InvalidTagException(RootModel[Any]):
    root: Any


class IssueCertificateResponse(BaseModel):
    CertificateArn: Optional[Arn] = None


class KeyAlgorithm(Enum):
    RSA_2048 = 'RSA_2048'
    RSA_4096 = 'RSA_4096'
    EC_prime256v1 = 'EC_prime256v1'
    EC_secp384r1 = 'EC_secp384r1'


class KeyStorageSecurityStandard(Enum):
    FIPS_140_2_LEVEL_2_OR_HIGHER = 'FIPS_140_2_LEVEL_2_OR_HIGHER'
    FIPS_140_2_LEVEL_3_OR_HIGHER = 'FIPS_140_2_LEVEL_3_OR_HIGHER'


class KeyUsage(BaseModel):
    CRLSign: Optional[Boolean] = None
    DataEncipherment: Optional[Boolean] = None
    DecipherOnly: Optional[Boolean] = None
    DigitalSignature: Optional[Boolean] = None
    EncipherOnly: Optional[Boolean] = None
    KeyAgreement: Optional[Boolean] = None
    KeyCertSign: Optional[Boolean] = None
    KeyEncipherment: Optional[Boolean] = None
    NonRepudiation: Optional[Boolean] = None


class LimitExceededException(RootModel[Any]):
    root: Any


class LockoutPreventedException(RootModel[Any]):
    root: Any


class MalformedCSRException(RootModel[Any]):
    root: Any


class MalformedCertificateException(RootModel[Any]):
    root: Any


class MaxResults(RootModel[conint(ge=1, le=1000)]):
    root: conint(ge=1, le=1000)


class NextToken(RootModel[constr(min_length=1, max_length=500)]):
    root: constr(min_length=1, max_length=500)


class OcspConfiguration(BaseModel):
    Enabled: Boolean
    OcspCustomCname: Optional[CnameString] = None


class PermanentDeletionTimeInDays(RootModel[conint(ge=7, le=30)]):
    root: conint(ge=7, le=30)


class PermissionAlreadyExistsException(RootModel[Any]):
    root: Any


class PolicyQualifierId(Enum):
    CPS = 'CPS'


class PositiveLong(RootModel[conint(ge=1)]):
    root: conint(ge=1)


class Principal(RootModel[constr(pattern=r'^[^*]+$', min_length=0, max_length=128)]):
    root: constr(pattern=r'^[^*]+$', min_length=0, max_length=128)


class PutPolicyRequest(BaseModel):
    Policy: AWSPolicy
    ResourceArn: Arn


class RequestAlreadyProcessedException(RootModel[Any]):
    root: Any


class RequestFailedException(RootModel[Any]):
    root: Any


class RequestInProgressException(RootModel[Any]):
    root: Any


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class ResourceOwner(Enum):
    SELF = 'SELF'
    OTHER_ACCOUNTS = 'OTHER_ACCOUNTS'


class RestoreCertificateAuthorityRequest(BaseModel):
    CertificateAuthorityArn: Arn


class RevocationReason(Enum):
    UNSPECIFIED = 'UNSPECIFIED'
    KEY_COMPROMISE = 'KEY_COMPROMISE'
    CERTIFICATE_AUTHORITY_COMPROMISE = 'CERTIFICATE_AUTHORITY_COMPROMISE'
    AFFILIATION_CHANGED = 'AFFILIATION_CHANGED'
    SUPERSEDED = 'SUPERSEDED'
    CESSATION_OF_OPERATION = 'CESSATION_OF_OPERATION'
    PRIVILEGE_WITHDRAWN = 'PRIVILEGE_WITHDRAWN'
    A_A_COMPROMISE = 'A_A_COMPROMISE'


class S3BucketName(RootModel[constr(min_length=3, max_length=63)]):
    root: constr(min_length=3, max_length=63)


class S3BucketName3To255(
    RootModel[constr(pattern=r'^[-a-zA-Z0-9._/]+$', min_length=3, max_length=255)]
):
    root: constr(pattern=r'^[-a-zA-Z0-9._/]+$', min_length=3, max_length=255)


class S3Key(RootModel[constr(max_length=1024)]):
    root: constr(max_length=1024)


class S3ObjectAcl(Enum):
    PUBLIC_READ = 'PUBLIC_READ'
    BUCKET_OWNER_FULL_CONTROL = 'BUCKET_OWNER_FULL_CONTROL'


class SigningAlgorithm(Enum):
    SHA256WITHECDSA = 'SHA256WITHECDSA'
    SHA384WITHECDSA = 'SHA384WITHECDSA'
    SHA512WITHECDSA = 'SHA512WITHECDSA'
    SHA256WITHRSA = 'SHA256WITHRSA'
    SHA384WITHRSA = 'SHA384WITHRSA'
    SHA512WITHRSA = 'SHA512WITHRSA'


class String(RootModel[str]):
    root: str


class String128(RootModel[constr(min_length=0, max_length=128)]):
    root: constr(min_length=0, max_length=128)


class String16(RootModel[constr(min_length=0, max_length=16)]):
    root: constr(min_length=0, max_length=16)


class String1To256(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class String253(RootModel[constr(min_length=0, max_length=253)]):
    root: constr(min_length=0, max_length=253)


class String256(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class String3(RootModel[constr(min_length=0, max_length=3)]):
    root: constr(min_length=0, max_length=3)


class String39(RootModel[constr(min_length=0, max_length=39)]):
    root: constr(min_length=0, max_length=39)


class String40(RootModel[constr(min_length=0, max_length=40)]):
    root: constr(min_length=0, max_length=40)


class String5(RootModel[constr(min_length=0, max_length=5)]):
    root: constr(min_length=0, max_length=5)


class String64(RootModel[constr(min_length=0, max_length=64)]):
    root: constr(min_length=0, max_length=64)


class TStamp(RootModel[datetime]):
    root: datetime


class TagKey(
    RootModel[
        constr(pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=1, max_length=128)
    ]
):
    root: constr(
        pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=1, max_length=128
    )


class TagValue(
    RootModel[
        constr(pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=0, max_length=256)
    ]
):
    root: constr(
        pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=0, max_length=256
    )


class TooManyTagsException(RootModel[Any]):
    root: Any


class ValidityPeriodType(Enum):
    END_DATE = 'END_DATE'
    ABSOLUTE = 'ABSOLUTE'
    DAYS = 'DAYS'
    MONTHS = 'MONTHS'
    YEARS = 'YEARS'


class XAmzTarget(Enum):
    ACMPrivateCA_CreateCertificateAuthority = 'ACMPrivateCA.CreateCertificateAuthority'


class XAmzTarget1(Enum):
    ACMPrivateCA_CreateCertificateAuthorityAuditReport = (
        'ACMPrivateCA.CreateCertificateAuthorityAuditReport'
    )


class XAmzTarget2(Enum):
    ACMPrivateCA_CreatePermission = 'ACMPrivateCA.CreatePermission'


class XAmzTarget3(Enum):
    ACMPrivateCA_DeleteCertificateAuthority = 'ACMPrivateCA.DeleteCertificateAuthority'


class XAmzTarget4(Enum):
    ACMPrivateCA_DeletePermission = 'ACMPrivateCA.DeletePermission'


class XAmzTarget5(Enum):
    ACMPrivateCA_DeletePolicy = 'ACMPrivateCA.DeletePolicy'


class XAmzTarget6(Enum):
    ACMPrivateCA_DescribeCertificateAuthority = (
        'ACMPrivateCA.DescribeCertificateAuthority'
    )


class XAmzTarget7(Enum):
    ACMPrivateCA_DescribeCertificateAuthorityAuditReport = (
        'ACMPrivateCA.DescribeCertificateAuthorityAuditReport'
    )


class XAmzTarget8(Enum):
    ACMPrivateCA_GetCertificate = 'ACMPrivateCA.GetCertificate'


class XAmzTarget9(Enum):
    ACMPrivateCA_GetCertificateAuthorityCertificate = (
        'ACMPrivateCA.GetCertificateAuthorityCertificate'
    )


class XAmzTarget10(Enum):
    ACMPrivateCA_GetCertificateAuthorityCsr = 'ACMPrivateCA.GetCertificateAuthorityCsr'


class XAmzTarget11(Enum):
    ACMPrivateCA_GetPolicy = 'ACMPrivateCA.GetPolicy'


class XAmzTarget12(Enum):
    ACMPrivateCA_ImportCertificateAuthorityCertificate = (
        'ACMPrivateCA.ImportCertificateAuthorityCertificate'
    )


class XAmzTarget13(Enum):
    ACMPrivateCA_IssueCertificate = 'ACMPrivateCA.IssueCertificate'


class XAmzTarget14(Enum):
    ACMPrivateCA_ListCertificateAuthorities = 'ACMPrivateCA.ListCertificateAuthorities'


class XAmzTarget15(Enum):
    ACMPrivateCA_ListPermissions = 'ACMPrivateCA.ListPermissions'


class XAmzTarget16(Enum):
    ACMPrivateCA_ListTags = 'ACMPrivateCA.ListTags'


class XAmzTarget17(Enum):
    ACMPrivateCA_PutPolicy = 'ACMPrivateCA.PutPolicy'


class XAmzTarget18(Enum):
    ACMPrivateCA_RestoreCertificateAuthority = (
        'ACMPrivateCA.RestoreCertificateAuthority'
    )


class XAmzTarget19(Enum):
    ACMPrivateCA_RevokeCertificate = 'ACMPrivateCA.RevokeCertificate'


class XAmzTarget20(Enum):
    ACMPrivateCA_TagCertificateAuthority = 'ACMPrivateCA.TagCertificateAuthority'


class XAmzTarget21(Enum):
    ACMPrivateCA_UntagCertificateAuthority = 'ACMPrivateCA.UntagCertificateAuthority'


class XAmzTarget22(Enum):
    ACMPrivateCA_UpdateCertificateAuthority = 'ACMPrivateCA.UpdateCertificateAuthority'


class AccessMethod(BaseModel):
    AccessMethodType_1: Optional[AccessMethodType] = Field(
        None, alias='AccessMethodType'
    )
    CustomObjectIdentifier_1: Optional[CustomObjectIdentifier] = Field(
        None, alias='CustomObjectIdentifier'
    )


class ActionList(RootModel[List[ActionType]]):
    root: List[ActionType] = Field(..., max_length=3, min_length=1)


class CreateCertificateAuthorityAuditReportRequest(BaseModel):
    AuditReportResponseFormat_1: AuditReportResponseFormat = Field(
        ..., alias='AuditReportResponseFormat'
    )
    CertificateAuthorityArn: Arn
    S3BucketName_1: S3BucketName = Field(..., alias='S3BucketName')


class CreateCertificateAuthorityAuditReportResponse(BaseModel):
    AuditReportId_1: Optional[AuditReportId] = Field(None, alias='AuditReportId')
    S3Key_1: Optional[S3Key] = Field(None, alias='S3Key')


class CreatePermissionRequest(BaseModel):
    Actions: ActionList
    CertificateAuthorityArn: Arn
    Principal_1: Principal = Field(..., alias='Principal')
    SourceAccount: Optional[AccountId] = None


class CrlConfiguration(BaseModel):
    CustomCname: Optional[CnameString] = None
    Enabled: Boolean
    ExpirationInDays: Optional[Integer1To5000] = None
    S3BucketName: Optional[S3BucketName3To255] = None
    S3ObjectAcl_1: Optional[S3ObjectAcl] = Field(None, alias='S3ObjectAcl')


class CustomAttribute(BaseModel):
    ObjectIdentifier: CustomObjectIdentifier
    Value: String1To256


class CustomAttributeList(RootModel[List[CustomAttribute]]):
    root: List[CustomAttribute] = Field(..., max_length=30, min_length=1)


class CustomExtension(BaseModel):
    Critical: Optional[Boolean] = None
    ObjectIdentifier: CustomObjectIdentifier
    Value: Base64String1To4096


class CustomExtensionList(RootModel[List[CustomExtension]]):
    root: List[CustomExtension] = Field(..., max_length=20, min_length=1)


class DeleteCertificateAuthorityRequest(BaseModel):
    CertificateAuthorityArn: Arn
    PermanentDeletionTimeInDays_1: Optional[PermanentDeletionTimeInDays] = Field(
        None, alias='PermanentDeletionTimeInDays'
    )


class DeletePermissionRequest(BaseModel):
    CertificateAuthorityArn: Arn
    Principal_1: Principal = Field(..., alias='Principal')
    SourceAccount: Optional[AccountId] = None


class DescribeCertificateAuthorityAuditReportResponse(BaseModel):
    AuditReportStatus_1: Optional[AuditReportStatus] = Field(
        None, alias='AuditReportStatus'
    )
    CreatedAt: Optional[TStamp] = None
    S3BucketName_1: Optional[S3BucketName] = Field(None, alias='S3BucketName')
    S3Key_1: Optional[S3Key] = Field(None, alias='S3Key')


class EdiPartyName(BaseModel):
    NameAssigner: Optional[String256] = None
    PartyName: String256


class ExtendedKeyUsage(BaseModel):
    ExtendedKeyUsageObjectIdentifier: Optional[CustomObjectIdentifier] = None
    ExtendedKeyUsageType_1: Optional[ExtendedKeyUsageType] = Field(
        None, alias='ExtendedKeyUsageType'
    )


class ExtendedKeyUsageList(RootModel[List[ExtendedKeyUsage]]):
    root: List[ExtendedKeyUsage] = Field(..., max_length=20, min_length=1)


class ListCertificateAuthoritiesRequest(BaseModel):
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    ResourceOwner_1: Optional[ResourceOwner] = Field(None, alias='ResourceOwner')


class ListPermissionsRequest(BaseModel):
    CertificateAuthorityArn: Arn
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class ListTagsRequest(BaseModel):
    CertificateAuthorityArn: Arn
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class OtherName(BaseModel):
    TypeId: CustomObjectIdentifier
    Value: String256


class Permission(BaseModel):
    Actions: Optional[ActionList] = None
    CertificateAuthorityArn: Optional[Arn] = None
    CreatedAt: Optional[TStamp] = None
    Policy: Optional[AWSPolicy] = None
    Principal_1: Optional[Principal] = Field(None, alias='Principal')
    SourceAccount: Optional[AccountId] = None


class PermissionList(RootModel[List[Permission]]):
    root: List[Permission] = Field(..., min_length=0)


class Qualifier(BaseModel):
    CpsUri: String256


class RevocationConfiguration(BaseModel):
    CrlConfiguration_1: Optional[CrlConfiguration] = Field(
        None, alias='CrlConfiguration'
    )
    OcspConfiguration_1: Optional[OcspConfiguration] = Field(
        None, alias='OcspConfiguration'
    )


class RevokeCertificateRequest(BaseModel):
    CertificateAuthorityArn: Arn
    CertificateSerial: String128
    RevocationReason_1: RevocationReason = Field(..., alias='RevocationReason')


class Tag(BaseModel):
    Key: TagKey
    Value: Optional[TagValue] = None


class TagList(RootModel[List[Tag]]):
    root: List[Tag] = Field(..., max_length=50, min_length=1)


class UntagCertificateAuthorityRequest(BaseModel):
    CertificateAuthorityArn: Arn
    Tags: TagList


class UpdateCertificateAuthorityRequest(BaseModel):
    CertificateAuthorityArn: Arn
    RevocationConfiguration_1: Optional[RevocationConfiguration] = Field(
        None, alias='RevocationConfiguration'
    )
    Status: Optional[CertificateAuthorityStatus] = None


class Validity(BaseModel):
    Type: ValidityPeriodType
    Value: PositiveLong


class ASN1Subject(BaseModel):
    CommonName: Optional[String64] = None
    Country: Optional[CountryCodeString] = None
    CustomAttributes: Optional[CustomAttributeList] = None
    DistinguishedNameQualifier: Optional[ASN1PrintableString64] = None
    GenerationQualifier: Optional[String3] = None
    GivenName: Optional[String16] = None
    Initials: Optional[String5] = None
    Locality: Optional[String128] = None
    Organization: Optional[String64] = None
    OrganizationalUnit: Optional[String64] = None
    Pseudonym: Optional[String128] = None
    SerialNumber: Optional[ASN1PrintableString64] = None
    State: Optional[String128] = None
    Surname: Optional[String40] = None
    Title: Optional[String64] = None


class GeneralName(BaseModel):
    DirectoryName: Optional[ASN1Subject] = None
    DnsName: Optional[String253] = None
    EdiPartyName_1: Optional[EdiPartyName] = Field(None, alias='EdiPartyName')
    IpAddress: Optional[String39] = None
    OtherName_1: Optional[OtherName] = Field(None, alias='OtherName')
    RegisteredId: Optional[CustomObjectIdentifier] = None
    Rfc822Name: Optional[String256] = None
    UniformResourceIdentifier: Optional[String253] = None


class GeneralNameList(RootModel[List[GeneralName]]):
    root: List[GeneralName] = Field(..., max_length=20, min_length=1)


class ListPermissionsResponse(BaseModel):
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    Permissions: Optional[PermissionList] = None


class ListTagsResponse(BaseModel):
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    Tags: Optional[TagList] = None


class PolicyQualifierInfo(BaseModel):
    PolicyQualifierId_1: PolicyQualifierId = Field(..., alias='PolicyQualifierId')
    Qualifier_1: Qualifier = Field(..., alias='Qualifier')


class PolicyQualifierInfoList(RootModel[List[PolicyQualifierInfo]]):
    root: List[PolicyQualifierInfo] = Field(..., max_length=20, min_length=1)


class TagCertificateAuthorityRequest(BaseModel):
    CertificateAuthorityArn: Arn
    Tags: TagList


class AccessDescription(BaseModel):
    AccessLocation: GeneralName
    AccessMethod_1: AccessMethod = Field(..., alias='AccessMethod')


class AccessDescriptionList(RootModel[List[AccessDescription]]):
    root: List[AccessDescription]


class CsrExtensions(BaseModel):
    KeyUsage_1: Optional[KeyUsage] = Field(None, alias='KeyUsage')
    SubjectInformationAccess: Optional[AccessDescriptionList] = None


class PolicyInformation(BaseModel):
    CertPolicyId: CustomObjectIdentifier
    PolicyQualifiers: Optional[PolicyQualifierInfoList] = None


class CertificateAuthorityConfiguration(BaseModel):
    CsrExtensions_1: Optional[CsrExtensions] = Field(None, alias='CsrExtensions')
    KeyAlgorithm_1: KeyAlgorithm = Field(..., alias='KeyAlgorithm')
    SigningAlgorithm_1: SigningAlgorithm = Field(..., alias='SigningAlgorithm')
    Subject: ASN1Subject


class CertificatePolicyList(RootModel[List[PolicyInformation]]):
    root: List[PolicyInformation] = Field(..., max_length=20, min_length=1)


class CreateCertificateAuthorityRequest(BaseModel):
    CertificateAuthorityConfiguration_1: CertificateAuthorityConfiguration = Field(
        ..., alias='CertificateAuthorityConfiguration'
    )
    CertificateAuthorityType_1: CertificateAuthorityType = Field(
        ..., alias='CertificateAuthorityType'
    )
    IdempotencyToken_1: Optional[IdempotencyToken] = Field(
        None, alias='IdempotencyToken'
    )
    KeyStorageSecurityStandard_1: Optional[KeyStorageSecurityStandard] = Field(
        None, alias='KeyStorageSecurityStandard'
    )
    RevocationConfiguration_1: Optional[RevocationConfiguration] = Field(
        None, alias='RevocationConfiguration'
    )
    Tags: Optional[TagList] = None
    UsageMode: Optional[CertificateAuthorityUsageMode] = None


class Extensions(BaseModel):
    CertificatePolicies: Optional[CertificatePolicyList] = None
    CustomExtensions: Optional[CustomExtensionList] = None
    ExtendedKeyUsage: Optional[ExtendedKeyUsageList] = None
    KeyUsage_1: Optional[KeyUsage] = Field(None, alias='KeyUsage')
    SubjectAlternativeNames: Optional[GeneralNameList] = None


class ApiPassthrough(BaseModel):
    Extensions_1: Optional[Extensions] = Field(None, alias='Extensions')
    Subject: Optional[ASN1Subject] = None


class CertificateAuthority(BaseModel):
    Arn_1: Optional[Arn] = Field(None, alias='Arn')
    CertificateAuthorityConfiguration_1: Optional[CertificateAuthorityConfiguration] = (
        Field(None, alias='CertificateAuthorityConfiguration')
    )
    CreatedAt: Optional[TStamp] = None
    FailureReason_1: Optional[FailureReason] = Field(None, alias='FailureReason')
    KeyStorageSecurityStandard_1: Optional[KeyStorageSecurityStandard] = Field(
        None, alias='KeyStorageSecurityStandard'
    )
    LastStateChangeAt: Optional[TStamp] = None
    NotAfter: Optional[TStamp] = None
    NotBefore: Optional[TStamp] = None
    OwnerAccount: Optional[AccountId] = None
    RestorableUntil: Optional[TStamp] = None
    RevocationConfiguration_1: Optional[RevocationConfiguration] = Field(
        None, alias='RevocationConfiguration'
    )
    Serial: Optional[String] = None
    Status: Optional[CertificateAuthorityStatus] = None
    Type: Optional[CertificateAuthorityType] = None
    UsageMode: Optional[CertificateAuthorityUsageMode] = None


class DescribeCertificateAuthorityResponse(BaseModel):
    CertificateAuthority_1: Optional[CertificateAuthority] = Field(
        None, alias='CertificateAuthority'
    )


class IssueCertificateRequest(BaseModel):
    ApiPassthrough_1: Optional[ApiPassthrough] = Field(None, alias='ApiPassthrough')
    CertificateAuthorityArn: Arn
    Csr: CsrBlob
    IdempotencyToken_1: Optional[IdempotencyToken] = Field(
        None, alias='IdempotencyToken'
    )
    SigningAlgorithm_1: SigningAlgorithm = Field(..., alias='SigningAlgorithm')
    TemplateArn: Optional[Arn] = None
    Validity_1: Validity = Field(..., alias='Validity')
    ValidityNotBefore: Optional[Validity] = None


class CertificateAuthorities(RootModel[List[CertificateAuthority]]):
    root: List[CertificateAuthority]


class ListCertificateAuthoritiesResponse(BaseModel):
    CertificateAuthorities_1: Optional[CertificateAuthorities] = Field(
        None, alias='CertificateAuthorities'
    )
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
